apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peering
spec:
  virtualRouters:
  - localASN: 64512   # Your K3s cluster ASN
    neighbors:
    - peerAddress: "192.168.1.1/32"  # Replace with your router’s IP
      peerASN: 64513                 # Replace with the ASN of your router
    serviceSelector:
      matchLabels:
        bgp: enabled
