# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  Corefile: ".:53 {\n    errors\n    health\n    ready\n    kubernetes cluster.local
    in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n
    \   }\n    hosts /etc/coredns/NodeHosts {\n      ttl 60\n      reload 15s\n      fallthrough\n
    \   }\n    prometheus :9153\n    forward . 192.168.1.1 \n    cache 30\n    loop\n
    \   reload\n    loadbalance\n    import /etc/coredns/custom/*.override\n}\nimport
    /etc/coredns/custom/*.server\n"
  NodeHosts: |
    192.168.10.21 k3s1
    192.168.10.23 k3s2
    192.168.10.30 k3s-master1
    192.168.10.31 k3s3
kind: ConfigMap
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4yQwWrzMBCEX0Xs2fEf20nsX9BDybH02lMva2kdq1Z2g6SkBJN3L8IUCiVtbyNGOzvfzoAn90IhOmHQcKmgAIsJQc+wl0CD8wQaSr1t1PzKSilFIUiIix4JfRoXHQjtdZHTuafAlCgq488xUSi9wK2Ayb
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2025-03-15T02:50:25Z"
  labels:
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "452514"
  uid: f2e53192-b1fb-4d12-865f-139574dee012
